apiVersion: networking.k8s.io/v1 #Directory Containing the Ingress Object
kind: Ingress #Type of Object
metadata: #Data about the Object
  name: ingress-srv #Name of the Object
spec: #Specification of the Object
  ingressClassName: nginx #Class of the Ingress
  rules: #Rules for the Ingress
    - host: posts.com #Host for the Ingress
      http:
        paths:
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 4002
          - path: /posts/?(.*)/comments
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments-srv
                port:
                  number: 4001
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000