#apiVersion: v1 #k8s is extensible - we can add in our own custom objects . This specifies the set of objects we want K8s to look at
#kind: Pod #The type of object we want to create
#metadata: #Config Options for object we are about to create
  #name: posts #When the Pod is created , give it a name of posts
#spec: #The exact attributes we want to apply to the object we are about to create
  #containers: #We can create many containers in a single pod
  #- name: posts #Make a container with a name of 'posts'
    #image: Yash02092003/posts:0.0.1 #The exact image we want to use
    #ports:
    #- containerPort: 4000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: yash02092003/posts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
